# Generated by Django 3.2.5 on 2021-07-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartphone',
            old_name='ram',
            new_name='processor_freq',
        ),
        migrations.AddField(
            model_name='laptop',
            name='ram',
            field=models.CharField(default=None, max_length=255, verbose_name='Оперативная память'),
        ),
    ]
