# Generated by Django 3.2.5 on 2021-07-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_product', '0006_auto_20210714_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Поставщик товара'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Поставщик товара'),
        ),
    ]
