# Generated by Django 3.2.5 on 2021-07-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_product', '0007_auto_20210714_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='discount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Кредитная карта'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='discount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Кредитная карта'),
        ),
    ]
