# Generated by Django 3.2.5 on 2021-07-17 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_product', '0012_auto_20210717_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_product.cart', verbose_name='Корзина'),
        ),
    ]
